### PR TITLE
RISC-V: Build RV64 multilib with mcmodel=medany

### PR DESCRIPTION
**Pull request by stephanosio**
This commit updates the Zephyr RISC-V multilib configurations to
explicitly specify `mcmodel=medany` when building the RV64 multilibs
because the GCC defaults to the `medlow` code model when the `mcmodel`
flag is not specified.

Note that the Zephyr build system builds the RV64 targets using the
`medany` code model because Zephyr uses the "flat" memory model and
the addressing capabilities of the `medlow` model is too limited for
it.

Signed-off-by: Stephanos Ioannidis <root@stephanos.io>

### CODE REVIEW

**Comment by keith-packard** [comment]
Hrm. Would it be better to change `TARGET_DEFAULT_CMODEL` instead? If someone builds a risc-v target with all memory lying below the 2GB boundary, they might actually want to use `medlow` instead, for efficiency? Locating libgcc.a (and other multi-lib libraries) depends on matching all of the specified compiler arguments in the multi-lib configuration. Including -mcmodel in the multi-lib configuration will keep something compiling with medlow from working. 

By changing`TARGET_DEFAULT_CMODEL` instead, we allow applications to specify whichever they prefer and things will still work -- code compiled with medany works fine with code compiled with medlow as long as the medlow range restrictions are respected. In particular, libgcc doesn't have any relocations which are affected by this flag. This also means applications not specifying any of these flags would also get medany.

Of course, by changing the default cmodel, we also break compatibility with other toolchains.

Alternatively, we can have the toolchain build everything for both cmodels; that way we'll ship libraries optimized for medlow as well as medany.

**Comment by stephanosio** [comment]
> Of course, by changing the default cmodel, we also break compatibility with other toolchains.

Yea, that concerns me. It will be very confusing for the Zephyr developers and users too.

> code compiled with medany works fine with code compiled with medlow as long as the medlow range restrictions are respected.

What do you think about handling this via `MULTILIB_REUSE`? For example:

```
MULTILIB_REUSE = \
...
march.rv64i_zicsr_zifencei/mabi.lp64/mcmodel.medany=march.rv64i_zicsr_zifencei/mabi.lp64 \
...
```

This way, `mcmodel=medany` should be used when no `mcmodel` flag is specified (i.e. `medlow`).

**Comment by keith-packard** [comment]
> This way, `mcmodel=medany` should be used when no `mcmodel` flag is specified (i.e. `medlow`).

If that works, it seems like a good solution. I'd be happy to test with picolibc (which is quite sensitive to these settings).

**Comment by stephanosio** [comment]
Re: https://github.com/zephyrproject-rtos/gcc/pull/11/commits/9a35bcc3b1e12176bacdd42d3b2f26ed70d4a328

```
$ ./riscv64-zephyr-elf-gcc -march=rv64i_zicsr_zifencei -mabi=lp64 --print-multi-directory
rv64i_zicsr_zifencei/lp64/medany
```

```
$ ./riscv64-zephyr-elf-gcc -march=rv64i_zicsr_zifencei -mabi=lp64 -mcmodel=medlow --print-multi-directory
rv64i_zicsr_zifencei/lp64/medany
```

```
$ ./riscv64-zephyr-elf-gcc -march=rv64i_zicsr_zifencei -mabi=lp64 -mcmodel=medany --print-multi-directory
rv64i_zicsr_zifencei/lp64/medany
```

**Review by keith-packard — APPROVED** [review]
I've tested this toolchain by building and testing picolibc; everything works now. Thanks!

**Pull request merged**
